language: cpp
compiler: gcc
dist: trusty
sudo: required
# switch back once wpilib-toolchain approved
#sudo: false
#addons:
#    apt:
#        sources:
#        - wpilib-toolchain
#        - ubuntu-toolchain-r-test
#        packages:
#        - gcc-5
#        - frc-toolchain
#        - libboost-test-dev
before_install:
- sudo apt-add-repository -y ppa:wpilib/toolchain
- sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get -y install gcc-5 g++-5 frc-toolchain libboost-test-dev
install:
- if [[ "$CXX" == "g++" ]]; then export CXX="g++-5" CC="gcc-5"; fi
- mkdir .wpilib
- wget -q -O .wpilib/release.zip http://first.wpi.edu/FRC/roborio/release.zip
- unzip -q -d .wpilib .wpilib/release.zip
- unzip -q -d .wpilib .wpilib/release/eclipse/plugins/edu.wpi.first.wpilib.plugins.cpp*.jar
- mkdir -p ~/wpilib/cpp/current
- unzip -q -d ~/wpilib/cpp/current .wpilib/resources/cpp.zip
script:
- cmake .
- make
- make ci-test
