dist: trusty
language: cpp
compiler: gcc

before_script:
    - sudo apt-add-repository -y ppa:wpilib/toolchain
    - sudo apt-get -qq update
    - sudo apt install -y frc-toolchain

script: cmake . && make ci-test
