sudo: false
language: cpp
compiler: gcc
addons:
    apt:
        sources:
        - wpilib-toolchain
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - frc-toolchain
        - libboost-test-dev
install:
- if [[ "$CXX" == "g++" ]]; then export CXX="g++-5" CC="gcc-5"; fi
- mkdir .wpilib
- wget -q -O .wpilib/release.zip http://first.wpi.edu/FRC/roborio/release.zip
- unzip -q -d .wpilib .wpilib/release.zip
- unzip -q -d .wpilib .wpilib/release/eclipse/plugins/edu.wpi.first.wpilib.plugins.cpp*.jar
- mkdir -p ~/wpilib/cpp/current
- unzip -q -d ~/wpilib/cpp/current .wpilib/resources/cpp.zip

script:
- cmake .
- make
- make ci-test
